In [ ]:
b='TS02EV1513'# ktm bike 2 wheeler
c='TS02MA0297'# vespa scooty 2 wheeler
d='KA10DL2121'# BMW car four wheeler
a=str(input("enter the vehicle number:"))
e=str(input("enter vehicle colour:"))
f=int(input("enter 2 or 4 or heavy vehicle:"))
if a==b:
    print(" vehicle"" number #matched# ")
    print("50% matched")
    if e=='orange':
        print("vehicle colour #matched#")
        print("75% matched")
        if f==2:
            print("type of wheeler #matched#")
            print("100% matched")
            print("stop the vehicle")
        else:
            print("type of wheeler not detected")
            print("only 50% matched")
    else:
        print(" vehicle colour does not match")
        print("only 50% matched")
else:
    print("vehicle number does not match")
    print("0% matched")

In [ ]:
b=int(input("enter a number:"))
c=int(input("enter a number:"))
if c>=b:
    for i in range(c,(c*b)+1,c):
         if i%b==0 and i%c==0:
            break
    print(i,"is the least common multiple")
else:
    for i in range(b,(c*b)+1,b):
          if i%b==0 and i%c==0:
            break
    print(i,"is the least common multiple")

In [ ]:
available_candies=50#int(input("enter the number of candies available:"))
candies=int(input("enter the number of candies required:"))
if available_candies==0:
    print("candies are out of stock")
else:
    for i in range(1,candies+1):
        print("candy",i)
        if i>=available_candies:
            print("candies are out of stock")
            break
        else:
            pass

In [ ]:
x=int(input("enter the number of units consumed:"))
y=int(x/100)*100
z=x%100# for calculating the cost for last 2 digits
a=100# calculating for every 100 units (constant)
p=10# it is to notify the z by which it should be multiplied
m=1 # just for print purpose
amount=0
for i in range(10,int(y/10)+1,10):
    print("current bill for",m,"th 100 units:",a*i)
    amount=amount+a*i
    p=p+10
    m=m+1

print("total bill=",amount+z*p)

In [ ]:
b=int(input("Number of workers needed to harvest 1 acre:"))
a=int(input("Enter the number of Quinta produced for 1 acre:"))
if a<=10:
    c=200
    print("wages for labour=",b*c)
else:
    if 10<a<=20:
        c=230
        print("wages for labour=",b*c)
    else:
         if a>20:
            c=260
            print("wages for labour=",b*c)

In [ ]:
a=int(input("Enter the number of Quinta produced for 1 acre:"))
y=int(a/10)*10
n=a%10
x=50
p=250
for i in range(10,y+1,10):
        print(p*x)
        p=p+50

In [ ]:
#factorial of a number
a=int(input("enter a number:"))
f=1
while a>0:
    f=f*a
    a=a-1
    print(f)

In [ ]:
print("a""manu")

In [ ]:
b='TS02EV1513'# ktm bike 2 wheeler
c='TS02MA0297'# vespa scooty 2 wheeler
d='KA10DL2121'# BMW car four wheeler
a=str(input("enter the vehicle number:"))
if a==b:
    print("ktm bike 2 wheeler vehicle"" number matched ")
    print("allow the vehicle inside")
else:
    if a==c:
        print("vespa scooty 2 wheeler vehicle"" number matched ")
        print("allow the vehicle inside")
    else:
        if a==d:
            print("BMW car 4 wheeler vehicle""number matched ")
            print("allow the vehicle inside")
        else:
            print("the vehicle number does not match with any of the vehicles belong to house")
            print("don't allow the vehicle inside")

In [3]:
a=str(input("enter a name:"))
b=len(a)
if b%2==0:
    print("the name is not palindrome")
else:
     i=0
     j=1
     while i<b/2:
       if a[i]==a[b-j]:
          print("the name is palindrome")
       i=i+1;
       j=j+1;
     else:
         print("the name is not palindrome")

enter a name:mmmm
the name is not palindrome

In [ ]:
print("enter the names of the couple")
a=str(input("enter the name of the male:"))
b=str(input("enter the name of the female:"))
if a=='narayana' and b=='appamma':
    print("couple 'NARAYANA' and 'APPAMMA' has two sons:\n1.CHINNA RAMAYA(younger)\n2.PEDDA RAMAYA(elder)")
    choose=int(input("choose one son:"))
    if choose==1:
        print("CHINNA RAMAYA\nANNAPURNA(wife)\n1.SARASWATHI(elder)\n2.VENKATESHWARLU(second elder)\n3.SRINIVASARAO(younger)"

enter the names of the couple

In [ ]:
#program to identify the common alphabets in the given two names
a=str(input("enter a name:"))
b=str(input("enter a name:"))
x=len(a)
y=len(b)
i=0
for i in range(0,x):
    j=0
    for j in range(0,y):
        if a[i]==b[j]:
            print(a[i])
            
    j=j+1
i=i+1

In [ ]:
print("the milk of buffallo doubles every next day")
a=int(input("the number of liters the buffallo gives on the nth day:"))
for i in range(1,a+1):
    x=a
    a=a*2
    print(x)

In [ ]:

a=str(input("Enter the arrivng point:"))
b=str(input("Enter the departure point:"))

if a=='khammam' and b=='hyderabad':
    print("1.Super luxury => khammam(6:00am) - hyderabad(9:30am)\n2.Express => khammam(6:30am) - hyderabad(10:35am)\n3.Ordinary => khammam(7:15am) - hyderabad(11:30am\n4.Rajadhani => khammam(8:00am) - hyderabad(11:10am)\n5.Indhira => khammam(8:25am) - hyderabad(11:45am) \n6.Morning star => khammam(10:00am) - hyderabad(12:30pm)\n7.Bhavani travels => khammam(11:35am) - hyderabad(2:45pm)")
    
    choose=int(input("choose a BUS:"))
    
    if choose==1:
        print("super luxury\nBUS.NO: TSUE1034\nSERVICE NO: 8\nkhammam(6:00am) - hyderabad(9:30am)\nSeats available: 43\nFare: 270.00 RS")
    elif choose==2:
        print("Express\nBUS.NO: TSME1255\nSERVICE NO: 2\nkhammam(6:30am) - hyderabad(10:35am)\nSeats available: 32\nFare: 250.00 RS")
    elif choose==3:
        print("Ordinary\nBUS.NO: TSMI9078\nSERVICE NO: 7\nkhammam(7:15am) - hyderabad(11:30am)\nSeats available: 18\nFare: 180.00 RS")
    elif choose==4:
        print("Rajadhani\nBUS.NO: TSkL6590\nSERVICE NO: 1\nkhammam(8:00am) - hyderabad(11:10am)\nSeats available: 25\nFare: 320.00 RS")
    elif choose==5:
        print("Indhira\nBUS.NO: TSJH1133\nSERVICE NO: 12\nkhammam(8:25am) - hyderabad(11:45am)\nSeats available: 08\nFare: 300.00 RS")
    elif choose==6:
        print("Morning star\nBUS.NO: TSUE2094\nSERVICE NO: 3\nkhammam(10:00am) - hyderabad(12:30pm)\nSeats available: 03\nFare: 350.00 RS")
    elif choose==7:
        print("Bhavani travels\nBUS.NO: TSLP1206\nSERVICE NO: 14\nkhammam(11:35am) - hyderabad(2:45am)\nSeats available: 43\nFare: 270.00 RS")
else:
    if a=='khammam' and b=='suryapeta':
        print("1.Super luxury => khammam(6:00am) - suryapeta(7:30am)\n2.Express => khammam(6:30am) - suryapeta(7:35am)\n3.Ordinary => khammam(7:15am) - suryapeta(8:30am\n4.Rajadhani => khammam(8:00am) - suryapeta(9:10am)\n5.Indhira => khammam(8:25am) - suryapeta(9:45am) \n6.Morning star => khammam(10:00am) - suryapeta(11:30pm)\n7.Bhavani travels => khammam(11:35am) - suryapeta(1:15pm)")
    
        choose=int(input("choose a BUS:"))
    
        if choose==1:
            print("super luxury\nBUS.NO: TSUE1034\nSERVICE NO: 8\nkhammam(6:00am) -suryapeta(7:30am)\nSeats available: 13\nFare: 100.00 RS")
        elif choose==2:
            print("Express\nBUS.NO: TSME1255\nSERVICE NO: 2\nkhammam(6:30am) - suryapeta(7:35am)\nSeats available: 22\nFare: 90.00 RS")
        elif choose==3:
             print("Ordinary\nBUS.NO: TSMI9078\nSERVICE NO: 7\nkhammam(7:15am) - suryapeta(8:30am)\nSeats available: 14\nFare: 60.00 RS")
        elif choose==4:
            print("Rajadhani\nBUS.NO: TSkL6590\nSERVICE NO: 1\nkhammam(8:00am) - suryapeta(9:10am)\nSeats available: 45\nFare: 100.00 RS")
        elif choose==5:
            print("Indhira\nBUS.NO: TSJH1133\nSERVICE NO: 12\nkhammam(8:25am) - suryapeta(9:45am)\nSeats available: 39\nFare: 100.00 RS")
        elif choose==6:
            print("Morning star\nBUS.NO: TSUE2094\nSERVICE NO: 3\nkhammam(10:00am) - suryapeta(11:30am)\nSeats available: 51\nFare: 120.00 RS")
        elif choose==7:
            print("Bhavani travels\nBUS.NO: TSLP1206\nSERVICE NO: 14\nkhammam(11:35am) - suryapeta(1:15pm)\nSeats available: 12\nFare: 130.00 RS")
        
    else:
        if a=='hyderabad' and b=='suryapeta':
            print("1.Super luxury => hyderabad(6:10am) - suryapeta(7:35am)\n2.Express => hydearabad(6:40am) - suryapeta(7:50am)\n3.Ordinary =>hydearabad(7:10am) - suryapeta(8:35am\n4.Rajadhani =>  hydearabad(8:00am) - suryapeta(9:15am)\n5.Indhira =>  hydearabad(8:20am) - suryapeta(9:50am) \n6.Morning star =>  hydearabad(10:00am) - suryapeta(11:30pm)\n7.Bhavani travels =>  hydearabad(11:45am) - suryapeta(1:25pm)")
    
            choose=int(input("choose a BUS:"))
    
            if choose==1:
                print("super luxury\nBUS.NO: TSUE1044\nSERVICE NO: 4\nhyderabad(6:00am) -suryapeta(7:30am)\nSeats available: 23\nFare: 110.00 RS")
            elif choose==2:
                print("Express\nBUS.NO: TSME1265\nSERVICE NO: 3\nhyderabad(6:30am) - suryapeta(7:35am)\nSeats available: 34\nFare: 100.00 RS")
            elif choose==3:
                print("Ordinary\nBUS.NO: TSMI988\nSERVICE NO: 9\nhyderabad(7:15am) - suryapeta(8:30am)\nSeats available: 12\nFare: 80.00 RS")
            elif choose==4:
                print("Rajadhani\nBUS.NO: TSkL6560\nSERVICE NO: 11\nhyderabad(8:00am) - suryapeta(9:10am)\nSeats available: 15\nFare: 95.00 RS")
            elif choose==5:
                print("Indhira\nBUS.NO: TSJH4133\nSERVICE NO: 14\nhyderabad(8:25am) - suryapeta(9:45am)\nSeats available: 26\nFare: 100.00 RS")
            elif choose==6:
                print("Morning star\nBUS.NO: TSUE2076\nSERVICE NO: 33\nhyderabad(10:00am) - suryapeta(11:30am)\nSeats available: 10\nFare: 110.00 RS")
            elif choose==7:
                print("Bhavani travels\nBUS.NO: TSLP1326\nSERVICE NO: 10\nhyderabad(11:35am) - suryapeta(1:15pm)\nSeats available: 19\nFare: 130.00 RS")
        else:
            if a=='hyderabad' and b=='khammam':
                print("1.Super luxury => hyderabad(6:10am) - khammam(7:35am)\n2.Express => hydearabad(6:40am) - khammam(7:50am)\n3.Ordinary =>hydearabad(7:10am) - khammam(8:35am\n4.Rajadhani =>  hydearabad(8:00am) - khammam(9:15am)\n5.Indhira =>  hydearabad(8:20am) - khammam(9:50am) \n6.Morning star =>  hydearabad(10:00am) - khammam(11:30pm)\n7.Bhavani travels =>  hyderabad(11:45am) - khammam(1:25pm)")
    
                choose=int(input("choose a BUS:"))
    
                if choose==1:
                   print("super luxury\nBUS.NO: TSUE1044\nSERVICE NO: 4\nhyderabad(6:00am) -khammam(10:30am)\nSeats available: 23\nFare: 250.00 RS")
                elif choose==2:
                    print("Express\nBUS.NO: TSME1265\nSERVICE NO: 3\nhyderabad(6:30am) - khammam(10:35am)\nSeats available: 33\nFare: 240.00 RS")
                elif choose==3:
                    print("Ordinary\nBUS.NO: TSMI988\nSERVICE NO: 9\nhyderabad(7:15am) - khammam(11:30am)\nSeats available: 25\nFare: 180.00 RS")
                elif choose==4:
                    print("Rajadhani\nBUS.NO: TSkL6560\nSERVICE NO: 11\nhyderabad(8:00am) - khammam(12:10am)\nSeats available: 35\nFare: 295.00 RS")
                elif choose==5:
                    print("Indhira\nBUS.NO: TSJH4133\nSERVICE NO: 14\nhyderabad(8:25am) - khammam(11:45am)\nSeats available: 56\nFare: 300.00 RS")
                elif choose==6:
                    print("Morning star\nBUS.NO: TSUE2076\nSERVICE NO: 33\nhyderabad(10:00am) - khammam(1:30pm)\nSeats available: 40\nFare: 310.00 RS")
                elif choose==7:
                    print("Bhavani travels\nBUS.NO: TSLP1326\nSERVICE NO: 10\nhyderabad(11:35am) - khammam(3:15pm)\nSeats available: 29\nFare: 330.00 RS")
            else:
                if a=='suryapeta' and b=='khammam':
                    print("1.Super luxury => suryapeta(6:10am) - khammam(7:35am)\n2.Express => suryapeta(6:40am) - khammam(7:50am)\n3.Ordinary =>suryapeta(7:10am) - khammam(8:35am\n4.Rajadhani =>  suryapeta(8:00am) - khammam(9:15am)\n5.Indhira =>  suryapeta(8:20am) - khammam(9:50am) \n6.Morning star =>  suryapeta(10:00am) - khammam(11:30pm)\n7.Bhavani travels =>  suryapeta(11:45am) - khammam(1:25pm)")
    
                    choose=int(input("choose a BUS:"))
    
                    if choose==1:
                       print("super luxury\nBUS.NO: TSUE1034\nSERVICE NO: 34\nsuryapeta(6:00am) -khammam(7:00am)\nSeats available: 24\nFare: 80.00 RS")
                    elif choose==2:
                        print("Express\nBUS.NO: TSME1235\nSERVICE NO: 32\nsuryapeta(6:30am) - khammam(7:35am)\nSeats available: 53\nFare: 100.00 RS")
                    elif choose==3:
                        print("Ordinary\nBUS.NO: TSMI948\nSERVICE NO: 19\nsuryapeta(7:15am) - khammam(8:30am)\nSeats available: 15\nFare: 110.00 RS")
                    elif choose==4:
                        print("Rajadhani\nBUS.NO: TSkL6660\nSERVICE NO: 41\nsuryapeta(8:00am) - khammam(9:10am)\nSeats available: 42\nFare: 95.00 RS")
                    elif choose==5:
                        print("Indhira\nBUS.NO: TSJH4173\nSERVICE NO: 24\nsuryapeta(8:25am) - khammam(9:45am)\nSeats available: 16\nFare: 120.00 RS")
                    elif choose==6:
                        print("Morning star\nBUS.NO: TSUE2976\nSERVICE NO: 23\nsuryapeta(10:00am) - khammam(11:30am)\nSeats available: 34\nFare: 110.00RS")
                    elif choose==7:
                        print("Bhavani travels\nBUS.NO: TSLP1526\nSERVICE NO: 11\nsuryapeta(11:35am) - khammam(12:40pm)\nSeats available: 21\nFare: 120.00 RS")
          
                else:
                    if a=='suryapeta' and b=='hyderabad':
                        print("1.Super luxury => suryapeta(6:10am) - hyderabad(7:35am)\n2.Express => suryapeta(6:40am) - hyderabad(7:50am)\n3.Ordinary =>suryapeta(7:10am) - hyderabad(8:35am\n4.Rajadhani =>  suryapeta(8:00am) - hyderabad(9:15am)\n5.Indhira =>  suryapeta(8:20am) - hyderabad(9:50am) \n6.Morning star =>  suryapeta(10:00am) - hyderabad(11:30pm)\n7.kesineni travels =>  suryapeta(11:45am) - hyderabad(1:25pm)")
    
                        choose=int(input("choose a BUS:"))
    
                        if choose==1:
                            print("super luxury\nBUS.NO: TSUE1032\nSERVICE NO: 14\nsuryapeta(6:00am) -hyderabad(9:20am)\nSeats available: 24\nFare: 150.00 RS")
                        elif choose==2:
                            print("Express\nBUS.NO: TSME1215\nSERVICE NO: 12\nsuryapeta(6:30am) - hyderabad(8:35am)\nSeats available: 53\nFare: 100.00 RS")
                        elif choose==3:
                            print("Ordinary\nBUS.NO: TSMI928\nSERVICE NO: 13\nsuryapeta(7:15am) - hyderabad(9:30am)\nSeats available: 15\nFare: 130.00 RS")
                        elif choose==4:
                            print("Rajadhani\nBUS.NO: TSkL6662\nSERVICE NO: 42\nsuryapeta(8:00am) - hyderabad(10:10am)\nSeats available: 42\nFare: 150.00 RS")
                        elif choose==5:
                            print("Indhira\nBUS.NO: TSJH4172\nSERVICE NO: 64\nsuryapeta(8:25am) - hyderabad(10:45am)\nSeats available: 16\nFare: 200.00 RS")
                        elif choose==6:
                            print("Morning star\nBUS.NO: TSUE2972\nSERVICE NO: 92\nsuryapeta(10:00am) - hyderabad(12:30pm)\nSeats available: 34\nFare: 210.00 RS")
                        elif choose==7:
                            print("kesineni travels\nBUS.NO: TSLP1522\nSERVICE NO: 37\nsuryapeta(11:35am) - hyderabad(1:40pm)\nSeats available: 21\nFare: 220.00 RS")
                    else:
                        print("No bus service available for the entered destination ")

In [14]:
customer_balance=9237.00
available_cash_atm=45000.00
print("welcome to punjab national bank")
pin=int(input("please enter your four digit PIN="))
if pin==2132:
    print("1.withdrawal \n2.balance enquiry\n3.mini statement\n4.PIN change")
    choose=int(input("choose an operation:"))
    if choose==1:
        amount=int(input("enter the amount="))
        if amount%100==0:
            if amount<=available_cash_atm:
                if amount<=customer_balance:
                    print("amount",amount)
                    print("availabale balance=",customer_balance-amount)
                else:
                    print("you have insufficient funds in your account")
            else:
                print("this machine is out of cash\nplease try entering the less amount")
        else:
            print("please enter the amount in 100 denominations")
    elif choose==2:
        print("avilabale balance=",availabale_balance)
    elif choose==3:
        print("mini statement:\n02-08-2020  2:30pm  debited 4300.00\n028-08-2020  1:450pm  credited 9000.00\n17-09-2020  10:30am  debited 1500.00")
    elif choose==4:
        pin1=int(input("enter your current pin"))
        if pin1==2132:
            pin2=int(input("enter your new pin"))
            print("your pin has been changed successfully")
        
else:
    pin=int(input("The entered PIN is incorrect\nplease re_enter the PIN="))
    if pin==2132:
        print("1.withdrawal \n2.balance enquiry\n3.mini statement\n4.PIN change\n5.Other services")
        choose=int(input("choose an operation:"))
        if choose==1:
            amount=int(input("enter the amount="))
            if amount%100==0:
                if amount<=available_cash_atm:
                    if amount<=customer_balance:
                        print("amount",amount)
                        print("availabale balance=",customer_balance-amount)
                    else:
                        print("you have insufficient funds in your account.")
                else:
                    print("this machine is out of cash\nplease try entering the less amount.")
            else:
                print("please enter the amount in 100 denominations.")
        elif choose==2:
            print("avilabale balance=",availabale_balance)
        elif choose==3:
            print("mini statement:\n02-08-2020  2:30pm  debited 4300.00\n028-08-2020  1:450pm  credited 9000.00\n17-09-2020  10:30am  debited 1500.00")
        elif choose==4:
            pin1=int(input("enter your current pin="))
            if pin1==2132:
                pin2=int(input("enter your new pin="))
                print("your pin has been changed successfuly.")
    else:
        pin=int(input("The entered PIN is incorrect\nplease re_enter the PIN="))
        if pin==2132:
            print("1.withdrawal \n2.balance enquiry\n3.mini statement\n4.PIN change\n5.Other services")
            choose=int(input("choose an operation:"))
            if choose==1:
                amount=int(input("enter the amount="))
                if amount%100==0:
                    if amount<=available_cash_atm:
                        if amount<=customer_balance:
                            print("amount",amount)
                            print("availabale balance=",customer_balance-amount)
                        else:
                            print("you have insufficient funds in your account.")
                    else:
                        print("this machine is out of cash\nplease try entering the less amount.")
                else:
                    print("please enter the amount in 100 denominations.")
            elif choose==2:
                print("avilabale balance=",availabale_balance)
            elif choose==3:
                print("mini statement:\n02-08-2020  2:30pm  debited 4300.00\n028-08-2020  1:450pm  credited 9000.00\n17-09-2020  10:30am  debited 1500.00")
            elif choose==4:
                pin1=int(input("enter your current pin="))
                if pin1==2132:
                    pin2=int(input("enter your new pin="))
                    print("your pin has been changed successfully.")
        else:
            print("your account has been temporarily blocked for security issues.")

welcome to punjab national bank
please enter your four digit PIN=2132
1.withdrawal
2.balance enquiry
3.mini statement
4.PIN change
choose an operation:1
enter the amount=4523
please enter the amount in 100 denominations

In [1]:
print("manu")

manu

In [ ]:
2*1++

In [25]:
a=str(input("enter a name"))
b=str(input("enter a name"))
set{'a' or 'b' }

SyntaxError: invalid syntax (<ipython-input-25-2c91d5365420>, line 3)

In [ ]:
print

In [26]:
print("hello")

hello

In [46]:
for i in range(1,10):
    for j in range(1,10):
        print(j,end="")

123456789123456789123456789123456789123456789123456789123456789123456789123456789

In [70]:
for i in range(1,11):
    if i==3:
        continue
    print(i)

1
2
4
5
6
7
8
9
10

In [90]:
x='manohar'
a=[] 
b=[]
c=[]
d=[]
e=[]
f=[]
g=[]
h=[]
i=[]
j=[]
k=[]
l=[]
m=[]
n=[]
o=[]
p=[]
q=[]
r=[]
s=[]
t=[]
u=[]
v=[]
w=[]
x=[]
y=[]
z=[]
for i in x:
    if i=='a' or i=='A':
        a.append(i)
    elif i=='b' or i=='B':
        b.append(i)
    elif i=='c' or i=='C':
        c.append(i)
    elif i=='d' or i=='D':
        d.append(i) 
    elif i=='e' or i=='E':
        e.append(i)
    elif i=='f' or i=='F':
        f.append(i)
    elif i=='g' or i=='G':
        g.append(i) 
    elif i=='h' or i=='H':
        h.append(i)
    elif i=='i' or i=='I':
        i.append(i)
    elif i=='j' or i=='J':
        j.append(i)
    elif i=='k' or i=='K':
        k.append(i)
    elif i=='l' or i=='L':
        l.append(i)
    elif i=='m' or i=='M':
        m.append(i)
    elif i=='n' or i=='N':
        n.append(i)
    elif i=='o' or i=='O':
        o.append(i)
    elif i=='p' or i=='P' :
        p.append(i) 
    elif i=='q' or i=='Q':
        q.append(i)
    elif i=='r' or i=='R':
        r.append(i)
    elif i=='s' or i=='S':
        s.append(i) 
    elif i=='t' or i=='T':
        t.append(i)
    elif i=='u' or i=='U':
        u.append(i)
    elif i=='v' or i=='V':
        v.append(i)
    elif i=='w' or i=='W':
        w.append(i)
    elif i=='x' or i=='X':
        x.append(i)
    elif i=='y' or i=='Y':
        y.append(i)
    elif i=='z' or i=='Z':
        z.append(i)
print(a)        
        
print("number of a letters:",len(a))
print("number of b letters:",len(b))
print("number of c letters:",len(c))
print("number of d letters:",len(d))
print("number of e letters:",len(e))
print("number of f letters:",len(f))
print("number of g letters:",len(g))
print("number of h letters:",len(h))
print("number of i letters:",len(i))
print("number of j letters:",len(j))
print("number of k letters:",len(k))
print("number of l letters:",len(l))
print("number of m letters:",len(m))
print("number of n letters:",len(n))
print("number of o letters:",len(o))
print("number of p letters:",len(p))
print("number of q letters:",len(q))
print("number of r letters:",len(r))
print("number of s letters:",len(s))
print("number of t letters:",len(t))
print("number of u letters:",len(u))
print("number of v letters:",len(v))
print("number of w letters:",len(w))
print("number of x letters:",len(x))
print("number of y letters:",len(y))
print("number of z letters:",len(z))

[]
number of a letters: 0
number of b letters: 0
number of c letters: 0
number of d letters: 0
number of e letters: 0
number of f letters: 0
number of g letters: 0
number of h letters: 0
number of i letters: 0
number of j letters: 0
number of k letters: 0
number of l letters: 0
number of m letters: 0
number of n letters: 0
number of o letters: 0
number of p letters: 0
number of q letters: 0
number of r letters: 0
number of s letters: 0
number of t letters: 0
number of u letters: 0
number of v letters: 0
number of w letters: 0
number of x letters: 0
number of y letters: 0
number of z letters: 0

In [ ]:
a='manu'
x=[]
for i in a:
    if i==
    x.append(i)
print(x)
len(x)

In [ ]:
#TS02EV1513
#TS12RW1265
#TS87RV1678
a=str(input("enter a number:"))
if a='TS02EV1513' or 
    print("rajadhani")

In [ ]:
dict={1:'rajdhani',2:'rajdhani',3:'ordinary'}
x=int(input("enter bus number"))
print(dict[x])